/* Generated by buildbot */

user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.chrome.favicons", false);
user_pref("dom.disable_window_move_resize", false);
user_pref("dom.disable_window_flip", false);
user_pref("browser.sessionstore.enabled", false);
user_pref("browser.sessionstore.resume_from_crash", false);
user_pref("dom.disable_open_during_load", false);
user_pref("javascript.options.showInConsole", true);
user_pref("browser.dom.window.dump.enabled", true);
user_pref("layout.fire_onload_after_image_background_loads", true);
user_pref("dom.allow_scripts_to_close_windows", true);
user_pref("privacy.popups.firstTime", false);
user_pref("browser.chrome.site_icons", false);
