# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := All
### Rules for final target.
$(obj).target/All.stamp: TOOLSET := $(TOOLSET)
$(obj).target/All.stamp: $(obj).target/src/common_audio/libspl.a $(obj).target/src/common_audio/libresampler.a $(obj).target/src/common_audio/libvad.a $(builddir)/common_audio_unittests $(builddir)/vie_auto_test $(builddir)/voe_auto_test $(builddir)/voe_cmd_test FORCE_DO_CMD
	$(call do_cmd,touch)

all_deps += $(obj).target/All.stamp
# Add target alias
.PHONY: All
All: $(obj).target/All.stamp

# Add target alias to "all" target.
.PHONY: all
all: All

