# ***** BEGIN LICENSE BLOCK *****
# Version: MPL 1.1/GPL 2.0/LGPL 2.1
#
# The contents of this file are subject to the Mozilla Public License Version
# 1.1 (the "License"); you may not use this file except in compliance with
# the License. You may obtain a copy of the License at
# http://www.mozilla.org/MPL/
#
# Software distributed under the License is distributed on an "AS IS" basis,
# WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
# for the specific language governing rights and limitations under the
# License.
#
# The Original Code is Mozilla Calendar code.
#
# The Initial Developer of the Original Code is Oracle Corporation
# Portions created by the Initial Developer are Copyright (C) 2008
# the Initial Developer. All Rights Reserved.
#
# Contributor(s):
#   Mike Shaver <shaver@mozilla.org>
#   Stuart Parmenter <stuart.parmenter@oracle.com>
#   Vladimir Vukicevic <vladimir@pobox.com>
#   Joey Minta <jminta@gmail.com>
#   Simon Paquet <bugzilla@babylonsounds.com>
#   Stefan Sitter <ssitter@googlemail.com>
#   Philipp Kewisch <mozilla@kewis.ch>
#   Michael Buettner <michael.buettner@sun.com>
#   Berend Cornelius <berend.cornelius@sun.com>
#
# Alternatively, the contents of this file may be used under the terms of
# either the GNU General Public License Version 2 or later (the "GPL"), or
# the GNU Lesser General Public License Version 2.1 or later (the "LGPL"),
# in which case the provisions of the GPL or the LGPL are applicable instead
# of those above. If you wish to allow use of your version of this file only
# under the terms of either the GPL or the LGPL, and not to allow others to
# use your version of this file under the terms of the MPL, indicate your
# decision by deleting the provisions above and replace them with the notice
# and other provisions required by the GPL or the LGPL. If you do not delete
# the provisions above, a recipient may use your version of this file under
# the terms of any one of the MPL, the GPL or the LGPL.
#
# ***** END LICENSE BLOCK ***** -->

<script type="application/javascript" src="chrome://lightning/content/lightning-utils.js"/>
<script type="application/javascript" src="chrome://lightning/content/messenger-overlay-sidebar.js"/>
<script type="application/javascript" src="chrome://lightning/content/messenger-overlay-toolbar.js"/>
<script type="application/javascript" src="chrome://lightning/content/lightning-common-sets.js"/>
<script type="application/javascript" src="chrome://calendar/content/calendar-invitations-manager.js"/>
<script type="application/javascript">
    var calendarmenulabel = "&lightning.calendar.label;";
    var calendarmenuaccesskey = "&lightning.calendar.accesskey;";
    var messagemenulabel = "&msgMenu.label;";
    var messagemenuaccesskey = "&msgMenu.accesskey;";
    var tasksmenulabel = "&lightning.tasks.label;";
    var tasksmenuaccesskey = "&lightning.tasks.accesskey;";
</script>
