# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1273257684);
user_pref("app.update.lastUpdateTime.background-update-timer", 1273257684);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1273257684);
user_pref("extensions.checkCompatibility.3.3a", false);
user_pref("intl.charsetmenu.mailview.cache", "windows-1252, ISO-8859-1, UTF-8");
user_pref("ldap_2.prefs_migrated", true);
user_pref("ldap_2.servers.default.filename", "default.mab");
user_pref("ldap_2.servers.default.replication.lastChangeNumber", 0);
user_pref("ldap_2.servers.default.uri", "moz-abldapdirectory://default.mab");
user_pref("ldap_2.servers.history.replication.lastChangeNumber", 0);
user_pref("ldap_2.servers.pab.replication.lastChangeNumber", 0);
user_pref("mail.account.account1.server", "server1");
user_pref("mail.account.account2.identities", "id4");
user_pref("mail.account.account2.server", "server2");
user_pref("mail.accountmanager.accounts", "account1,account2");
user_pref("mail.accountmanager.defaultaccount", "account2");
user_pref("mail.accountmanager.localfoldersserver", "server1");
user_pref("mail.attachment.store.version", 1);
user_pref("mail.folder.views.version", 1);
user_pref("mail.identity.id4.draft_folder", "imap://blaketestwinton@imap.gmail.com/Drafts");
user_pref("mail.identity.id4.drafts_folder_picker_mode", "0");
user_pref("mail.identity.id4.escapedVCard", "");
user_pref("mail.identity.id4.fcc_folder", "imap://blaketestwinton@imap.gmail.com/Sent");
user_pref("mail.identity.id4.fcc_folder_picker_mode", "0");
user_pref("mail.identity.id4.fullName", "Blake Winton");
user_pref("mail.identity.id4.organization", "");
user_pref("mail.identity.id4.reply_to", "");
user_pref("mail.identity.id4.smtpServer", "smtp2");
user_pref("mail.identity.id4.stationery_folder", "imap://blaketestwinton@imap.gmail.com/Templates");
user_pref("mail.identity.id4.tmpl_folder_picker_mode", "0");
user_pref("mail.identity.id4.useremail", "blaketestwinton@gmail.com");
user_pref("mail.identity.id4.valid", true);
user_pref("mail.preferences.compose.selectedTabIndex", 2);
user_pref("mail.preferences.display.selectedTabIndex", 1);
user_pref("mail.preferences.privacy.selectedTabIndex", 3);
user_pref("mail.root.imap", "AAAAAAHMAAIAAQxNYWNpbnRvc2ggSEQAAAAAAAAAAAAAAAAAAADE+gKpSCsAAAGd9dkISW1hcE1haWwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAZ32EMfg848AAAAAAAAAAP////8AAAkgAAAAAAAAAAAAAAAAAAAAFDFzaGNlbHhoLnRiMi1kZWZhdWx0ABAACAAAxPo66QAAABEACAAAx+ErzwAAAAEAGAGd9dkADiAPAA4gBwAKSrcACkq2AAB72AACAFVNYWNpbnRvc2ggSEQ6VXNlcnM6YndpbnRvbjpMaWJyYXJ5OlRodW5kZXJiaXJkOlByb2ZpbGVzOjFzaGNlbHhoLnRiMi1kZWZhdWx0OkltYXBNYWlsAAAOABIACABJAG0AYQBwAE0AYQBpAGwADwAaAAwATQBhAGMAaQBuAHQAbwBzAGgAIABIAEQAEgBIVXNlcnMvYndpbnRvbi9MaWJyYXJ5L1RodW5kZXJiaXJkL1Byb2ZpbGVzLzFzaGNlbHhoLnRiMi1kZWZhdWx0L0ltYXBNYWlsABMAAS8AABUAAgAO//8AAA==");
user_pref("mail.root.imap-rel", "[ProfD]ImapMail");
user_pref("mail.root.none", "AAAAAAG8AAIAAQxNYWNpbnRvc2ggSEQAAAAAAAAAAAAAAAAAAADE+gKpSCsAAAGd9dkETWFpbAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAZ32Ccfg848AAAAAAAAAAP////8AAAkgAAAAAAAAAAAAAAAAAAAAFDFzaGNlbHhoLnRiMi1kZWZhdWx0ABAACAAAxPo66QAAABEACAAAx+ErzwAAAAEAGAGd9dkADiAPAA4gBwAKSrcACkq2AAB72AACAFFNYWNpbnRvc2ggSEQ6VXNlcnM6YndpbnRvbjpMaWJyYXJ5OlRodW5kZXJiaXJkOlByb2ZpbGVzOjFzaGNlbHhoLnRiMi1kZWZhdWx0Ok1haWwAAA4ACgAEAE0AYQBpAGwADwAaAAwATQBhAGMAaQBuAHQAbwBzAGgAIABIAEQAEgBEVXNlcnMvYndpbnRvbi9MaWJyYXJ5L1RodW5kZXJiaXJkL1Byb2ZpbGVzLzFzaGNlbHhoLnRiMi1kZWZhdWx0L01haWwAEwABLwAAFQACAA7//wAA");
user_pref("mail.root.none-rel", "[ProfD]Mail");
user_pref("mail.root.pop3", "AAAAAAG8AAIAAQxNYWNpbnRvc2ggSEQAAAAAAAAAAAAAAAAAAADE+gKpSCsAAAG+viQETWFpbAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAb6+eMgJ1KoAAAAAAAAAAP////8AAAkgAAAAAAAAAAAAAAAAAAAAFDFzaGNlbHhoLnRiMi1kZWZhdWx0ABAACAAAxPo66QAAABEACAAAyAoM6gAAAAEAGAG+viQADiAPAA4gBwAKSrcACkq2AAB72AACAFFNYWNpbnRvc2ggSEQ6VXNlcnM6YndpbnRvbjpMaWJyYXJ5OlRodW5kZXJiaXJkOlByb2ZpbGVzOjFzaGNlbHhoLnRiMi1kZWZhdWx0Ok1haWwAAA4ACgAEAE0AYQBpAGwADwAaAAwATQBhAGMAaQBuAHQAbwBzAGgAIABIAEQAEgBEVXNlcnMvYndpbnRvbi9MaWJyYXJ5L1RodW5kZXJiaXJkL1Byb2ZpbGVzLzFzaGNlbHhoLnRiMi1kZWZhdWx0L01haWwAEwABLwAAFQACAA7//wAA");
user_pref("mail.root.pop3-rel", "[ProfD]Mail");
user_pref("mail.server.server1.directory", "AAAAAAHeAAIAAQxNYWNpbnRvc2ggSEQAAAAAAAAAAAAAAAAAAADE+gKpSCsAAAG+vngNTG9jYWwgRm9sZGVycwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAb6+ecgJ1KoAAAAAAAAAAP////8AAAkgAAAAAAAAAAAAAAAAAAAABE1haWwAEAAIAADE+jrpAAAAEQAIAADICgzqAAAAAQAcAb6+eAG+viQADiAPAA4gBwAKSrcACkq2AAB72AACAF9NYWNpbnRvc2ggSEQ6VXNlcnM6YndpbnRvbjpMaWJyYXJ5OlRodW5kZXJiaXJkOlByb2ZpbGVzOjFzaGNlbHhoLnRiMi1kZWZhdWx0Ok1haWw6TG9jYWwgRm9sZGVycwAADgAcAA0ATABvAGMAYQBsACAARgBvAGwAZABlAHIAcwAPABoADABNAGEAYwBpAG4AdABvAHMAaAAgAEgARAASAFJVc2Vycy9id2ludG9uL0xpYnJhcnkvVGh1bmRlcmJpcmQvUHJvZmlsZXMvMXNoY2VseGgudGIyLWRlZmF1bHQvTWFpbC9Mb2NhbCBGb2xkZXJzABMAAS8AABUAAgAO//8AAA==");
user_pref("mail.server.server1.directory-rel", "[ProfD]Mail/Local Folders");
user_pref("mail.server.server1.hostname", "Local Folders");
user_pref("mail.server.server1.name", "Local Folders");
user_pref("mail.server.server1.type", "none");
user_pref("mail.server.server1.userName", "nobody");
user_pref("mail.server.server2.capability", 811553);
user_pref("mail.server.server2.check_new_mail", false);
user_pref("mail.server.server2.directory", "AAAAAAHuAAIAAQxNYWNpbnRvc2ggSEQAAAAAAAAAAAAAAAAAAADE+gKpSCsAAAG+vjEOaW1hcC5nbWFpbC5jb20AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAb6/KcgJ1ngAAAAAAAAAAP////8AAAkgAAAAAAAAAAAAAAAAAAAACEltYXBNYWlsABAACAAAxPo66QAAABEACAAAyAoOuAAAAAEAHAG+vjEBvr4kAA4gDwAOIAcACkq3AApKtgAAe9gAAgBkTWFjaW50b3NoIEhEOlVzZXJzOmJ3aW50b246TGlicmFyeTpUaHVuZGVyYmlyZDpQcm9maWxlczoxc2hjZWx4aC50YjItZGVmYXVsdDpJbWFwTWFpbDppbWFwLmdtYWlsLmNvbQAOAB4ADgBpAG0AYQBwAC4AZwBtAGEAaQBsAC4AYwBvAG0ADwAaAAwATQBhAGMAaQBuAHQAbwBzAGgAIABIAEQAEgBXVXNlcnMvYndpbnRvbi9MaWJyYXJ5L1RodW5kZXJiaXJkL1Byb2ZpbGVzLzFzaGNlbHhoLnRiMi1kZWZhdWx0L0ltYXBNYWlsL2ltYXAuZ21haWwuY29tAAATAAEvAAAVAAIADv//AAA=");
user_pref("mail.server.server2.directory-rel", "[ProfD]ImapMail/imap.gmail.com");
user_pref("mail.server.server2.download_on_biff", true);
user_pref("mail.server.server2.hostname", "imap.gmail.com");
user_pref("mail.server.server2.login_at_startup", false);
user_pref("mail.server.server2.max_cached_connections", 5);
user_pref("mail.server.server2.name", "blaketestwinton@gmail.com");
user_pref("mail.server.server2.namespace.personal", "\"\"");
user_pref("mail.server.server2.port", 993);
user_pref("mail.server.server2.realhostname", "imap.googlemail.com");
user_pref("mail.server.server2.socketType", 3);
user_pref("mail.server.server2.type", "imap");
user_pref("mail.server.server2.userName", "blaketestwinton");
user_pref("mail.shell.checkDefaultClient", false);
user_pref("mail.showFolderPaneColumns", true);
user_pref("mail.smtp.defaultserver", "smtp2");
user_pref("mail.smtpserver.smtp1.description", "Gmail");
user_pref("mail.smtpserver.smtp1.hostname", "smtp.gmail.com");
user_pref("mail.smtpserver.smtp1.port", 587);
user_pref("mail.smtpserver.smtp1.try_ssl", 2);
user_pref("mail.smtpserver.smtp1.username", "blaketestwinton");
user_pref("mail.smtpserver.smtp2.description", "Gmail");
user_pref("mail.smtpserver.smtp2.hostname", "smtp.gmail.com");
user_pref("mail.smtpserver.smtp2.port", 587);
user_pref("mail.smtpserver.smtp2.try_ssl", 2);
user_pref("mail.smtpserver.smtp2.username", "mozillatest");
user_pref("mail.smtpservers", "smtp2,smtp1");
user_pref("mail.spam.version", 1);
user_pref("mail.startup.enabledMailCheckOnce", true);
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "1.8.1.24");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("mailnews.ui.threadpane.version", 5);
user_pref("pref.downloads.disable_button.edit_actions", false);
user_pref("wallet.caveat", true);
