#! /bin/sh
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

add_makefiles "
mailnews/Makefile
mailnews/addrbook/Makefile
mailnews/addrbook/public/Makefile
mailnews/addrbook/src/Makefile
mailnews/addrbook/test/Makefile
mailnews/base/Makefile
mailnews/base/ispdata/Makefile
mailnews/base/public/Makefile
mailnews/base/search/public/Makefile
mailnews/base/search/src/Makefile
mailnews/base/src/Makefile
mailnews/base/test/Makefile
mailnews/base/util/Makefile
mailnews/build/Makefile
mailnews/compose/Makefile
mailnews/compose/public/Makefile
mailnews/compose/src/Makefile
mailnews/compose/test/Makefile
mailnews/db/Makefile
mailnews/db/gloda/Makefile
mailnews/db/gloda/components/Makefile
mailnews/db/gloda/modules/Makefile
mailnews/db/gloda/test/Makefile
mailnews/db/msgdb/Makefile
mailnews/db/msgdb/public/Makefile
mailnews/db/msgdb/src/Makefile
mailnews/db/msgdb/test/Makefile
mailnews/extensions/Makefile
mailnews/extensions/bayesian-spam-filter/Makefile
mailnews/extensions/bayesian-spam-filter/src/Makefile
mailnews/extensions/bayesian-spam-filter/test/Makefile
mailnews/extensions/fts3/Makefile
mailnews/extensions/fts3/public/Makefile
mailnews/extensions/fts3/src/Makefile
mailnews/extensions/mailviews/Makefile
mailnews/extensions/mailviews/public/Makefile
mailnews/extensions/mailviews/content/Makefile
mailnews/extensions/mailviews/src/Makefile
mailnews/extensions/mdn/Makefile
mailnews/extensions/mdn/src/Makefile
mailnews/extensions/newsblog/Makefile
mailnews/extensions/offline-startup/Makefile
mailnews/extensions/smime/Makefile
mailnews/extensions/smime/public/Makefile
mailnews/extensions/smime/src/Makefile
mailnews/imap/Makefile
mailnews/imap/public/Makefile
mailnews/imap/src/Makefile
mailnews/imap/test/Makefile
mailnews/import/Makefile
mailnews/import/applemail/src/Makefile
mailnews/import/build/Makefile
mailnews/import/eudora/src/Makefile
mailnews/import/oexpress/Makefile
mailnews/import/outlook/src/Makefile
mailnews/import/public/Makefile
mailnews/import/src/Makefile
mailnews/import/test/Makefile
mailnews/import/text/src/Makefile
mailnews/import/vcard/src/Makefile
mailnews/import/winlivemail/Makefile
mailnews/local/Makefile
mailnews/local/public/Makefile
mailnews/local/src/Makefile
mailnews/local/test/Makefile
mailnews/mapi/mapiDll/Makefile
mailnews/mapi/mapihook/Makefile
mailnews/mapi/mapihook/build/Makefile
mailnews/mapi/mapihook/public/Makefile
mailnews/mapi/mapihook/src/Makefile
mailnews/mime/Makefile
mailnews/mime/cthandlers/Makefile
mailnews/mime/cthandlers/glue/Makefile
mailnews/mime/cthandlers/smimestub/Makefile
mailnews/mime/cthandlers/vcard/Makefile
mailnews/mime/emitters/Makefile
mailnews/mime/emitters/src/Makefile
mailnews/mime/public/Makefile
mailnews/mime/src/Makefile
mailnews/mime/test/Makefile
mailnews/news/Makefile
mailnews/news/public/Makefile
mailnews/news/src/Makefile
mailnews/news/test/Makefile
mailnews/test/performance/bloat/Makefile
"
