# This file is generated by gyp; do not edit.

export builddir_name ?= trunk/third_party_mods/libjingle/$(OBJDIR)/media/webrtc/out
.PHONY: all
all:
	$(MAKE) -C ../.. jsoncpp libjingle libjingle_p2p libjingle_app
