# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := peerconnection_client_dev
### Rules for final target.
$(obj).target/third_party_mods/libjingle/peerconnection_client_dev.stamp: TOOLSET := $(TOOLSET)
$(obj).target/third_party_mods/libjingle/peerconnection_client_dev.stamp: $(obj).target/third_party_mods/libjingle/libjingle_app.a FORCE_DO_CMD
	$(call do_cmd,touch)

all_deps += $(obj).target/third_party_mods/libjingle/peerconnection_client_dev.stamp
# Add target alias
.PHONY: peerconnection_client_dev
peerconnection_client_dev: $(obj).target/third_party_mods/libjingle/peerconnection_client_dev.stamp

