# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := peerconnection_unittests
### Rules for final target.
$(obj).target/third_party_mods/libjingle/peerconnection_unittests.stamp: TOOLSET := $(TOOLSET)
$(obj).target/third_party_mods/libjingle/peerconnection_unittests.stamp:  FORCE_DO_CMD
	$(call do_cmd,touch)

all_deps += $(obj).target/third_party_mods/libjingle/peerconnection_unittests.stamp
# Add target alias
.PHONY: peerconnection_unittests
peerconnection_unittests: $(obj).target/third_party_mods/libjingle/peerconnection_unittests.stamp

