/* -*- Mode: C++; tab-width: 2; indent-tabs-mode: nil; c-basic-offset: 2 -*- */
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */
#include "nsISupports.idl"
#include "nsIAbCard.idl"
#include "nsIAbDirectory.idl"

interface nsIAddrDBAnnouncer;

[scriptable, uuid(5d7e5a7a-1ac9-46dc-abfd-758c98be26e9)]
interface nsIAddrDBListener : nsISupports {

  void onCardAttribChange(in unsigned long abCode);

  /**
   * Handle the card entry change event.
   *
   * @param     aAbCode         The code to indicate the type of event
   *                            (see nsAddrDatabase.h AB_NOTIFY_CODE for values).
   * @param     aCard           The card entry on which the event occurred.
   * @param     aParent         The parent of card entry.
   *                            If set to null, the event can be ignored.
   *                            This happens during import & sync operations when
   *                            listeners of a database need not be notified about
   *                            card entry changes.
   */
  void onCardEntryChange (in unsigned long aAbCode,
                          in nsIAbCard aCard,
                          in nsIAbDirectory aParent);

  void onListEntryChange (in unsigned long abCode,
                          in nsIAbDirectory list);
  void onAnnouncerGoingAway();

};
