/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"
#include "nsISimpleEnumerator.idl"

interface nsIAbDirectory;

[scriptable, uuid(ad61b4fc-d8d8-40b2-b924-4c10f28a8a17)]
interface nsIAbDirFactory : nsISupports
{
    /**
     * Get a top level address book directory and sub directories, given some
     * properties.
     *
     * @param aDirName  Name of the address book
     *
     * @param aURI      URI of the address book
     *
     * @param aPrefName Pref name for the preferences of the address book
     *
     * @return          Enumeration of nsIAbDirectory interfaces
     */
    nsISimpleEnumerator getDirectories(in AString aDirName, in ACString aURI,
                                       in ACString aPrefName);

    /**
     * Delete a top level address book directory
     * 
     */
    void deleteDirectory (in nsIAbDirectory directory);
};

