/* -*- Mode: IDL; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"

interface nsIURI;
interface nsIMsgWindow;
interface nsIUrlListener;
interface nsIMsgFolder;

[scriptable, uuid(f465a3ee-5b29-4da6-8b2e-d764bcba468e)]
interface nsILocalMailIncomingServer : nsISupports
{
  /// Create the necessary default folders that must always exist in an account (e.g. Inbox/Trash).
  void createDefaultMailboxes();

  /// Set special folder flags on the default folders.
  void setFlagsOnDefaultMailboxes();

  nsIURI getNewMail(in nsIMsgWindow aMsgWindow, in nsIUrlListener aUrlListener, in nsIMsgFolder aInbox);
};

