/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"
#include "nsIUrlListener.idl"

interface nsIURI;
interface nsIStreamListener;
interface nsIMsgWindow;
interface nsIFile;

[scriptable, uuid(809FCD02-B9EA-4DC0-84F0-3FBC55AE11F1)]
interface nsIMailboxService : nsISupports {

  /*
   * All of these functions build mailbox urls and run them. If you want a
   * handle on the running task, pass in a valid nsIURI ptr. You can later
   * interrupt this action by asking the netlib service manager to interrupt
   * the url you are given back. Remember to release aURL when you are done
   * with it. Pass nullptr in for aURL if you don't care about the returned URL.
   */

  /*
   * Pass in a file path for the mailbox you wish to parse. You also need to
   * pass in a mailbox  parser (the consumer). The url listener can be null
   * if you have no interest in tracking the url.
   */
  nsIURI ParseMailbox(in nsIMsgWindow aMsgWindow, in nsIFile aMailboxPath,
                                 in nsIStreamListener aMailboxParser,
                                 in nsIUrlListener aUrlListener);

};
