/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"

[scriptable, uuid(4b31bdd9-6f4c-46d4-a766-a94f11b599bc)]
interface nsIRssService : nsISupports 
{
};
