/* -*- Mode: idl; tab-width: 2; indent-tabs-mode: nil; c-basic-offset: 2 -*- */
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"

#include "calIRecurrenceItem.idl"

interface calIItemBase;
interface calIDateTime;

interface calIIcalProperty;

// an interface implementing a RDATE or EXDATE

[scriptable, uuid(c5b331d4-b470-475b-9497-db9e2731e559)]
interface calIRecurrenceDate : calIRecurrenceItem
{
  //
  // recurrence date set
  //
  attribute calIDateTime date;
};
