/* -*- Mode: IDL; tab-width: 50; indent-tabs-mode: nil; c-basic-offset: 2 -*- */
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"

[scriptable, uuid(404c7d78-bec7-474c-aa2a-82c0d0563bb6)]
interface calIErrors : nsISupports
{
  /**
   * The first two constants are copied from nsError.h, but named slightly
   * differently, because if they're named the same, the names collide and
   * the compiler can't deal.
   */
  const unsigned long CAL_ERROR_MODULE_CALENDAR = 5;
  const unsigned long CAL_ERROR_MODULE_BASE_OFFSET = 0x45;

  /**
   * The beginning of this set of error codes, also copied from the macros
   * in nsError.h.
   */
  const unsigned long ERROR_BASE = (1<<31) | 
    (CAL_ERROR_MODULE_CALENDAR + CAL_ERROR_MODULE_BASE_OFFSET) << 16;

  /* Onto the actual errors! */

  /**
   * An invalid or nonexistent timezone was encountered.
   */
  const unsigned long INVALID_TIMEZONE = ERROR_BASE + 1;

  /**
   * Attempted to modify a readOnly calendar.
   */
  const unsigned long CAL_IS_READONLY = ERROR_BASE + 2;  

  /**
   * Error while decoding an (ics) file from utf8
   */
  const unsigned long CAL_UTF8_DECODING_FAILED = ERROR_BASE + 3;
  
  /**
   * Tried to add an item to a calendar in which an item with the
   * same ID already existed
   */
  const unsigned long DUPLICATE_ID = ERROR_BASE + 4;

  /**
   * Operation has been cancelled.
   */
  const unsigned long OPERATION_CANCELLED = ERROR_BASE + 5;

  /**
   * Creation of calendar object failed
   */
  const unsigned long PROVIDER_CREATION_FAILED = ERROR_BASE + 6;

  /**
   * Profile data has newer schema than we know in this calendar version.
   */
  const unsigned long STORAGE_UNKNOWN_SCHEMA_ERROR = ERROR_BASE + 7;

  /**
   * Profile data may refer to newer timezones than we know.
   */
  const unsigned long STORAGE_UNKNOWN_TIMEZONES_ERROR = ERROR_BASE + 8;

  /**
   * The calendar could not be accessed for reading.
   */
  const unsigned long READ_FAILED = ERROR_BASE + 9;

  /**
   * The calendar could not be accessed for modification.
   */
  const unsigned long MODIFICATION_FAILED = ERROR_BASE + 10;

  /* ICS specific errors */
  const unsigned long ICS_ERROR_BASE = ERROR_BASE + 0x100;

  /**
   * ICS errors, copied from icalerror.h.
   * The numbers (minus ICS_ERROR_BASE) should match with the enum
   * values from icalerror.h
   */
  const unsigned long ICS_NO_ERROR = ICS_ERROR_BASE + 0;
  const unsigned long ICS_BADARG = ICS_ERROR_BASE + 1;
  const unsigned long ICS_NEWFAILED = ICS_ERROR_BASE + 2;
  const unsigned long ICS_ALLOCATION = ICS_ERROR_BASE + 3;
  const unsigned long ICS_MALFORMEDDATA = ICS_ERROR_BASE + 4;
  const unsigned long ICS_PARSE = ICS_ERROR_BASE + 5;
  const unsigned long ICS_INTERNAL = ICS_ERROR_BASE + 6;
  const unsigned long ICS_FILE = ICS_ERROR_BASE + 7;
  const unsigned long ICS_USAGE = ICS_ERROR_BASE + 8;
  const unsigned long ICS_UNIMPLEMENTED = ICS_ERROR_BASE + 9;
  const unsigned long ICS_UNKNOWN = ICS_ERROR_BASE + 10;
  
  /**
   * WCAP specific errors, defined in
   * calendar/providers/wcap/public/calIWcapErrors.idl
   * Range claimed is [ERROR_BASE + 0x200, ERROR_BASE + 0x300)
   */
  const unsigned long WCAP_ERROR_BASE = ERROR_BASE + 0x200;

  /**
   * (Cal)DAV specific errors
   * Range is [ERROR_BASE + 0x301, ERROR_BASE + 0x399]
   */
  const unsigned long DAV_ERROR_BASE = ERROR_BASE + 0x301;
  const unsigned long DAV_NOT_DAV = DAV_ERROR_BASE +  0;
  const unsigned long DAV_DAV_NOT_CALDAV = DAV_ERROR_BASE + 1;
  const unsigned long DAV_NO_PROPS = DAV_ERROR_BASE +  2;
  const unsigned long DAV_PUT_ERROR = DAV_ERROR_BASE + 3;
  const unsigned long DAV_REMOVE_ERROR = DAV_ERROR_BASE + 4;
  const unsigned long DAV_REPORT_ERROR = DAV_ERROR_BASE + 5;
};

