/* -*- Mode: IDL; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"

interface nsIMsgNewsFolder;

[scriptable, uuid(921AC214-96B5-11d2-B7EB-00805F05FFA5)]
interface nsINNTPArticleList : nsISupports {
    void initialize(in nsIMsgNewsFolder newsFolder); 
    void addArticleKey(in long key);
    void finishAddingArticleKeys();
};

