/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"
#include "nsrootidl.idl"

%{C++
#define NS_IMIMEHEADERS_CONTRACTID \
  "@mozilla.org/messenger/mimeheaders;1"
%}

/** 
 * An interface that can extract individual headers from a body of headers.
 */ 
[scriptable, uuid(877af00d-1ce8-446a-b4ce-b7cb1edd2791)]
interface nsIMimeHeaders : nsISupports {
  /// Feed in the text of headers
  void initialize(in ACString allHeaders);

  /**
   * Get the text of a header.
   *
   * Leading and trailing whitespace from headers will be stripped from the
   * return value. If getAllOfThem is set to true, then the returned string will
   * have all of the values of the header, in order, joined with the ',\r\n\t'.
   *
   * If the header is not present, then the returned value is NULL.
   */
  ACString extractHeader(in string headerName, in boolean getAllOfThem);

  /// The current text of all header data.
  readonly attribute ACString allHeaders;
};
