# This file is generated by gyp; do not edit.

export builddir_name ?= trunk/src/common_audio/$(OBJDIR)/media/webrtc/out
.PHONY: all
all:
	$(MAKE) -C ../.. signal_processing vad resampler vad_unittests signal_processing_unittests resampler_unittests
