# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

  <!-- NEEDED FOR MULTIPLE CALENDAR SUPPORT -->
  <script type="application/javascript" src="chrome://calendar/content/calendar-management.js"/>

  <!-- NEEDED FOR CLIPBOARD SUPPORT -->
  <script type="application/javascript" src="chrome://calendar/content/calendar-clipboard.js"/>

  <!-- NEEDED FOR IMPORT / EXPORT SUPPORT -->
  <script type="application/javascript" src="chrome://calendar/content/import-export.js"/>

  <!-- NEEDED FOR PUBLICATION SUPPORT -->
  <script type="application/javascript" src="chrome://calendar/content/publish.js"/>

  <script type="application/javascript" src="chrome://calendar/content/calendar-item-editing.js"/>
  <script type="application/javascript" src="chrome://calendar/content/calendar-chrome-startup.js"/>
  <script type="application/javascript" src="chrome://calendar/content/calUtils.js"/>
  <script type="application/javascript" src="chrome://calendar/content/mouseoverPreviews.js"/>
  <script type="application/javascript" src="chrome://calendar/content/calendar-views.js"/>
  <script type="application/javascript" src="chrome://calendar/content/calendar-ui-utils.js"/>
  <script type="application/javascript" src="chrome://calendar/content/calendar-creation.js"/>
  <script type="application/javascript" src="chrome://calendar/content/calendar-dnd-listener.js"/>
  <script type="application/javascript" src="chrome://calendar/content/calendar-statusbar.js"/>
  <script type="application/javascript" src="chrome://global/content/nsDragAndDrop.js"/>

  <!-- NEEDED FOR TASK VIEW/LIST SUPPORT -->
  <script type="application/javascript" src="chrome://calendar/content/calendar-task-editing.js"/>

  <script type="application/javascript" src="chrome://calendar/content/calendar-extract.js"/>
