/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"
#include "nsIURI.idl"
#include "nsIFileStreams.idl"
#include "nsIFile.idl"

%{ C++

//
// Callback declarations for URL completion
//
// For completion of send/message creation operations...
typedef nsresult (*nsAttachSaveCompletionCallback) (nsresult aStatus,
                                                    const nsACString &aContentType,
                                                    const nsACString &aCharset,
                                                    int32_t totalSize, const PRUnichar* aMsg, 
                                                    void *tagData);

class nsMsgAttachmentHandler;
%}

native nsAttachSaveCompletionCallback(nsAttachSaveCompletionCallback);
[ptr] native nsMsgAttachmentHandler(nsMsgAttachmentHandler);


[noscript, uuid(7316af6b-050d-4697-9d39-b0b358514f5c)]
interface nsIURLFetcher : nsISupports
{
  boolean stillRunning();

  void fireURLRequest(in nsIURI aURL, in nsIFile localFile, in nsIOutputStream fileStream, in nsAttachSaveCompletionCallback cb, in nsMsgAttachmentHandler tagData);

  void initialize(in nsIFile localFile, in nsIOutputStream fileStream, in nsAttachSaveCompletionCallback cb, in nsMsgAttachmentHandler tagData);
};
