# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := audio_processing
DEFS_Debug := '-DNO_HEAPCHECKER' \
	'-DCHROMIUM_BUILD' \
	'-DENABLE_REMOTING=1' \
	'-DENABLE_P2P_APIS=1' \
	'-DENABLE_CONFIGURATION_POLICY' \
	'-DENABLE_GPU=1' \
	'-DENABLE_EGLIMAGE=1' \
	'-DUSE_SKIA=1' \
	'-DENABLE_REGISTER_PROTOCOL_HANDLER=1' \
	'-DWEBRTC_TARGET_PC' \
	'-DWEBRTC_LINUX' \
	'-DWEBRTC_THREAD_RR' \
	'-DWEBRTC_NS_FLOAT' \
	'-DGOOGLE_PROTOBUF_NO_RTTI' \
	'-D__STDC_FORMAT_MACROS' \
	'-DDYNAMIC_ANNOTATIONS_ENABLED=1' \
	'-DWTF_USE_DYNAMIC_ANNOTATIONS=1' \
	'-D_DEBUG'

# Flags passed to all source files.
CFLAGS_Debug := -Werror \
	-pthread \
	-fno-exceptions \
	-Wall \
	-Wno-unused-parameter \
	-Wno-missing-field-initializers \
	-D_FILE_OFFSET_BITS=64 \
	-fvisibility=hidden \
	-pipe \
	-fPIC \
	-fno-strict-aliasing \
	-O0 \
	-g

# Flags passed to only C files.
CFLAGS_C_Debug := 

# Flags passed to only C++ files.
CFLAGS_CC_Debug := -fno-rtti \
	-fno-threadsafe-statics \
	-fvisibility-inlines-hidden \
	-Wsign-compare

INCS_Debug := -Isrc \
	-I. \
	-Isrc/modules/audio_processing/main/interface \
	-Isrc/modules/interface \
	-I$(obj)/gen/protoc_out \
	-Isrc/modules/audio_processing/aec/main/interface \
	-Isrc/modules/audio_processing/aecm/main/interface \
	-Isrc/modules/audio_processing/agc/main/interface \
	-Isrc/common_audio/signal_processing_library/main/interface \
	-Isrc/common_audio/vad/main/interface \
	-Isrc/system_wrappers/interface \
	-Isrc/modules/audio_processing/ns/main/interface \
	-Ithird_party/protobuf \
	-Ithird_party/protobuf/src

DEFS_Release := '-DNO_HEAPCHECKER' \
	'-DCHROMIUM_BUILD' \
	'-DENABLE_REMOTING=1' \
	'-DENABLE_P2P_APIS=1' \
	'-DENABLE_CONFIGURATION_POLICY' \
	'-DENABLE_GPU=1' \
	'-DENABLE_EGLIMAGE=1' \
	'-DUSE_SKIA=1' \
	'-DENABLE_REGISTER_PROTOCOL_HANDLER=1' \
	'-DWEBRTC_TARGET_PC' \
	'-DWEBRTC_LINUX' \
	'-DWEBRTC_THREAD_RR' \
	'-DWEBRTC_NS_FLOAT' \
	'-DGOOGLE_PROTOBUF_NO_RTTI' \
	'-D__STDC_FORMAT_MACROS' \
	'-DNDEBUG' \
	'-DNVALGRIND' \
	'-DDYNAMIC_ANNOTATIONS_ENABLED=0'

# Flags passed to all source files.
CFLAGS_Release := -Werror \
	-pthread \
	-fno-exceptions \
	-Wall \
	-Wno-unused-parameter \
	-Wno-missing-field-initializers \
	-D_FILE_OFFSET_BITS=64 \
	-fvisibility=hidden \
	-pipe \
	-fPIC \
	-fno-strict-aliasing \
	-O2 \
	-fno-ident \
	-fdata-sections \
	-ffunction-sections

# Flags passed to only C files.
CFLAGS_C_Release := 

# Flags passed to only C++ files.
CFLAGS_CC_Release := -fno-rtti \
	-fno-threadsafe-statics \
	-fvisibility-inlines-hidden \
	-Wsign-compare

INCS_Release := -Isrc \
	-I. \
	-Isrc/modules/audio_processing/main/interface \
	-Isrc/modules/interface \
	-I$(obj)/gen/protoc_out \
	-Isrc/modules/audio_processing/aec/main/interface \
	-Isrc/modules/audio_processing/aecm/main/interface \
	-Isrc/modules/audio_processing/agc/main/interface \
	-Isrc/common_audio/signal_processing_library/main/interface \
	-Isrc/common_audio/vad/main/interface \
	-Isrc/system_wrappers/interface \
	-Isrc/modules/audio_processing/ns/main/interface \
	-Ithird_party/protobuf \
	-Ithird_party/protobuf/src

OBJS := $(obj).target/$(TARGET)/src/modules/audio_processing/main/source/audio_buffer.o \
	$(obj).target/$(TARGET)/src/modules/audio_processing/main/source/audio_processing_impl.o \
	$(obj).target/$(TARGET)/src/modules/audio_processing/main/source/echo_cancellation_impl.o \
	$(obj).target/$(TARGET)/src/modules/audio_processing/main/source/echo_control_mobile_impl.o \
	$(obj).target/$(TARGET)/src/modules/audio_processing/main/source/gain_control_impl.o \
	$(obj).target/$(TARGET)/src/modules/audio_processing/main/source/high_pass_filter_impl.o \
	$(obj).target/$(TARGET)/src/modules/audio_processing/main/source/level_estimator_impl.o \
	$(obj).target/$(TARGET)/src/modules/audio_processing/main/source/noise_suppression_impl.o \
	$(obj).target/$(TARGET)/src/modules/audio_processing/main/source/splitting_filter.o \
	$(obj).target/$(TARGET)/src/modules/audio_processing/main/source/processing_component.o \
	$(obj).target/$(TARGET)/src/modules/audio_processing/main/source/voice_detection_impl.o \
	$(obj).target/$(TARGET)/gen/protoc_out/webrtc/audio_processing/debug.pb.o

# Add to the list of files we specially track dependencies for.
all_deps += $(OBJS)

# Make sure our dependencies are built before any of us.
$(OBJS): | $(obj).target/src/modules/debug_proto.stamp

# CFLAGS et al overrides must be target-local.
# See "Target-specific Variable Values" in the GNU Make manual.
$(OBJS): TOOLSET := $(TOOLSET)
$(OBJS): GYP_CFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE)) $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_C_$(BUILDTYPE))
$(OBJS): GYP_CXXFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE)) $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_CC_$(BUILDTYPE))

# Suffix rules, putting all outputs into $(obj).

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(srcdir)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# Try building from generated source, too.

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj).$(TOOLSET)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# End of this set of suffix rules
### Rules for final target.
LDFLAGS_Debug := -pthread \
	-Wl,-z,noexecstack

LDFLAGS_Release := -pthread \
	-Wl,-z,noexecstack \
	-Wl,-O1 \
	-Wl,--as-needed \
	-Wl,--gc-sections

LIBS := 

$(obj).target/src/modules/libaudio_processing.a: GYP_LDFLAGS := $(LDFLAGS_$(BUILDTYPE))
$(obj).target/src/modules/libaudio_processing.a: LIBS := $(LIBS)
$(obj).target/src/modules/libaudio_processing.a: TOOLSET := $(TOOLSET)
$(obj).target/src/modules/libaudio_processing.a: $(OBJS) FORCE_DO_CMD
	$(call do_cmd,alink)

all_deps += $(obj).target/src/modules/libaudio_processing.a
# Add target alias
.PHONY: audio_processing
audio_processing: $(obj).target/src/modules/libaudio_processing.a

# Add target alias to "all" target.
.PHONY: all
all: audio_processing

