# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := iLBC
DEFS_Debug := '-DNO_HEAPCHECKER' \
	'-DCHROMIUM_BUILD' \
	'-DENABLE_REMOTING=1' \
	'-DENABLE_P2P_APIS=1' \
	'-DENABLE_CONFIGURATION_POLICY' \
	'-DENABLE_GPU=1' \
	'-DENABLE_EGLIMAGE=1' \
	'-DUSE_SKIA=1' \
	'-DENABLE_REGISTER_PROTOCOL_HANDLER=1' \
	'-DWEBRTC_TARGET_PC' \
	'-DWEBRTC_LINUX' \
	'-DWEBRTC_THREAD_RR' \
	'-D__STDC_FORMAT_MACROS' \
	'-DDYNAMIC_ANNOTATIONS_ENABLED=1' \
	'-DWTF_USE_DYNAMIC_ANNOTATIONS=1' \
	'-D_DEBUG'

# Flags passed to all source files.
CFLAGS_Debug := -Werror \
	-pthread \
	-fno-exceptions \
	-Wall \
	-Wno-unused-parameter \
	-Wno-missing-field-initializers \
	-D_FILE_OFFSET_BITS=64 \
	-fvisibility=hidden \
	-pipe \
	-fPIC \
	-fno-strict-aliasing \
	-O0 \
	-g

# Flags passed to only C files.
CFLAGS_C_Debug := 

# Flags passed to only C++ files.
CFLAGS_CC_Debug := -fno-rtti \
	-fno-threadsafe-statics \
	-fvisibility-inlines-hidden \
	-Wsign-compare

INCS_Debug := -Isrc \
	-I. \
	-Isrc/modules/audio_coding/codecs/iLBC/main/interface \
	-Isrc/common_audio/signal_processing_library/main/interface

DEFS_Release := '-DNO_HEAPCHECKER' \
	'-DCHROMIUM_BUILD' \
	'-DENABLE_REMOTING=1' \
	'-DENABLE_P2P_APIS=1' \
	'-DENABLE_CONFIGURATION_POLICY' \
	'-DENABLE_GPU=1' \
	'-DENABLE_EGLIMAGE=1' \
	'-DUSE_SKIA=1' \
	'-DENABLE_REGISTER_PROTOCOL_HANDLER=1' \
	'-DWEBRTC_TARGET_PC' \
	'-DWEBRTC_LINUX' \
	'-DWEBRTC_THREAD_RR' \
	'-D__STDC_FORMAT_MACROS' \
	'-DNDEBUG' \
	'-DNVALGRIND' \
	'-DDYNAMIC_ANNOTATIONS_ENABLED=0'

# Flags passed to all source files.
CFLAGS_Release := -Werror \
	-pthread \
	-fno-exceptions \
	-Wall \
	-Wno-unused-parameter \
	-Wno-missing-field-initializers \
	-D_FILE_OFFSET_BITS=64 \
	-fvisibility=hidden \
	-pipe \
	-fPIC \
	-fno-strict-aliasing \
	-O2 \
	-fno-ident \
	-fdata-sections \
	-ffunction-sections

# Flags passed to only C files.
CFLAGS_C_Release := 

# Flags passed to only C++ files.
CFLAGS_CC_Release := -fno-rtti \
	-fno-threadsafe-statics \
	-fvisibility-inlines-hidden \
	-Wsign-compare

INCS_Release := -Isrc \
	-I. \
	-Isrc/modules/audio_coding/codecs/iLBC/main/interface \
	-Isrc/common_audio/signal_processing_library/main/interface

OBJS := $(obj).target/$(TARGET)/src/modules/audio_coding/codecs/iLBC/main/source/abs_quant.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/codecs/iLBC/main/source/abs_quant_loop.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/codecs/iLBC/main/source/augmented_cb_corr.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/codecs/iLBC/main/source/bw_expand.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/codecs/iLBC/main/source/cb_construct.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/codecs/iLBC/main/source/cb_mem_energy.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/codecs/iLBC/main/source/cb_mem_energy_augmentation.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/codecs/iLBC/main/source/cb_mem_energy_calc.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/codecs/iLBC/main/source/cb_search.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/codecs/iLBC/main/source/cb_search_core.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/codecs/iLBC/main/source/cb_update_best_index.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/codecs/iLBC/main/source/chebyshev.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/codecs/iLBC/main/source/comp_corr.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/codecs/iLBC/main/source/constants.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/codecs/iLBC/main/source/create_augmented_vec.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/codecs/iLBC/main/source/decode.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/codecs/iLBC/main/source/decode_residual.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/codecs/iLBC/main/source/decoder_interpolate_lsf.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/codecs/iLBC/main/source/do_plc.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/codecs/iLBC/main/source/encode.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/codecs/iLBC/main/source/energy_inverse.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/codecs/iLBC/main/source/enh_upsample.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/codecs/iLBC/main/source/enhancer.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/codecs/iLBC/main/source/enhancer_interface.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/codecs/iLBC/main/source/filtered_cb_vecs.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/codecs/iLBC/main/source/frame_classify.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/codecs/iLBC/main/source/gain_dequant.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/codecs/iLBC/main/source/gain_quant.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/codecs/iLBC/main/source/get_cd_vec.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/codecs/iLBC/main/source/get_lsp_poly.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/codecs/iLBC/main/source/get_sync_seq.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/codecs/iLBC/main/source/hp_input.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/codecs/iLBC/main/source/hp_output.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/codecs/iLBC/main/source/ilbc.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/codecs/iLBC/main/source/index_conv_dec.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/codecs/iLBC/main/source/index_conv_enc.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/codecs/iLBC/main/source/init_decode.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/codecs/iLBC/main/source/init_encode.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/codecs/iLBC/main/source/interpolate.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/codecs/iLBC/main/source/interpolate_samples.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/codecs/iLBC/main/source/lpc_encode.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/codecs/iLBC/main/source/lsf_check.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/codecs/iLBC/main/source/lsf_interpolate_to_poly_dec.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/codecs/iLBC/main/source/lsf_interpolate_to_poly_enc.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/codecs/iLBC/main/source/lsf_to_lsp.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/codecs/iLBC/main/source/lsf_to_poly.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/codecs/iLBC/main/source/lsp_to_lsf.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/codecs/iLBC/main/source/my_corr.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/codecs/iLBC/main/source/nearest_neighbor.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/codecs/iLBC/main/source/pack_bits.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/codecs/iLBC/main/source/poly_to_lsf.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/codecs/iLBC/main/source/poly_to_lsp.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/codecs/iLBC/main/source/refiner.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/codecs/iLBC/main/source/simple_interpolate_lsf.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/codecs/iLBC/main/source/simple_lpc_analysis.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/codecs/iLBC/main/source/simple_lsf_dequant.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/codecs/iLBC/main/source/simple_lsf_quant.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/codecs/iLBC/main/source/smooth.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/codecs/iLBC/main/source/smooth_out_data.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/codecs/iLBC/main/source/sort_sq.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/codecs/iLBC/main/source/split_vq.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/codecs/iLBC/main/source/state_construct.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/codecs/iLBC/main/source/state_search.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/codecs/iLBC/main/source/swap_bytes.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/codecs/iLBC/main/source/unpack_bits.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/codecs/iLBC/main/source/vq3.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/codecs/iLBC/main/source/vq4.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/codecs/iLBC/main/source/window32_w32.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/codecs/iLBC/main/source/xcorr_coef.o

# Add to the list of files we specially track dependencies for.
all_deps += $(OBJS)

# CFLAGS et al overrides must be target-local.
# See "Target-specific Variable Values" in the GNU Make manual.
$(OBJS): TOOLSET := $(TOOLSET)
$(OBJS): GYP_CFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE)) $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_C_$(BUILDTYPE))
$(OBJS): GYP_CXXFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE)) $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_CC_$(BUILDTYPE))

# Suffix rules, putting all outputs into $(obj).

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(srcdir)/%.c FORCE_DO_CMD
	@$(call do_cmd,cc,1)

# Try building from generated source, too.

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj).$(TOOLSET)/%.c FORCE_DO_CMD
	@$(call do_cmd,cc,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj)/%.c FORCE_DO_CMD
	@$(call do_cmd,cc,1)

# End of this set of suffix rules
### Rules for final target.
LDFLAGS_Debug := -pthread \
	-Wl,-z,noexecstack

LDFLAGS_Release := -pthread \
	-Wl,-z,noexecstack \
	-Wl,-O1 \
	-Wl,--as-needed \
	-Wl,--gc-sections

LIBS := 

$(obj).target/src/modules/libiLBC.a: GYP_LDFLAGS := $(LDFLAGS_$(BUILDTYPE))
$(obj).target/src/modules/libiLBC.a: LIBS := $(LIBS)
$(obj).target/src/modules/libiLBC.a: TOOLSET := $(TOOLSET)
$(obj).target/src/modules/libiLBC.a: $(OBJS) FORCE_DO_CMD
	$(call do_cmd,alink)

all_deps += $(obj).target/src/modules/libiLBC.a
# Add target alias
.PHONY: iLBC
iLBC: $(obj).target/src/modules/libiLBC.a

# Add target alias to "all" target.
.PHONY: all
all: iLBC

