# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := NetEq
DEFS_Debug := '-DNO_HEAPCHECKER' \
	'-DCHROMIUM_BUILD' \
	'-DENABLE_REMOTING=1' \
	'-DENABLE_P2P_APIS=1' \
	'-DENABLE_CONFIGURATION_POLICY' \
	'-DENABLE_GPU=1' \
	'-DENABLE_EGLIMAGE=1' \
	'-DUSE_SKIA=1' \
	'-DENABLE_REGISTER_PROTOCOL_HANDLER=1' \
	'-DWEBRTC_TARGET_PC' \
	'-DWEBRTC_LINUX' \
	'-DWEBRTC_THREAD_RR' \
	'-DNETEQ_VOICEENGINE_CODECS' \
	'-DSCRATCH' \
	'-D__STDC_FORMAT_MACROS' \
	'-DDYNAMIC_ANNOTATIONS_ENABLED=1' \
	'-DWTF_USE_DYNAMIC_ANNOTATIONS=1' \
	'-D_DEBUG'

# Flags passed to all source files.
CFLAGS_Debug := -Werror \
	-pthread \
	-fno-exceptions \
	-Wall \
	-Wno-unused-parameter \
	-Wno-missing-field-initializers \
	-D_FILE_OFFSET_BITS=64 \
	-fvisibility=hidden \
	-pipe \
	-fPIC \
	-fno-strict-aliasing \
	-O0 \
	-g

# Flags passed to only C files.
CFLAGS_C_Debug := 

# Flags passed to only C++ files.
CFLAGS_CC_Debug := -fno-rtti \
	-fno-threadsafe-statics \
	-fvisibility-inlines-hidden \
	-Wsign-compare

INCS_Debug := -Isrc \
	-I. \
	-Isrc/modules/audio_coding/NetEQ/main/interface \
	-Isrc/modules/audio_coding/codecs/CNG/main/interface \
	-Isrc/common_audio/signal_processing_library/main/interface

DEFS_Release := '-DNO_HEAPCHECKER' \
	'-DCHROMIUM_BUILD' \
	'-DENABLE_REMOTING=1' \
	'-DENABLE_P2P_APIS=1' \
	'-DENABLE_CONFIGURATION_POLICY' \
	'-DENABLE_GPU=1' \
	'-DENABLE_EGLIMAGE=1' \
	'-DUSE_SKIA=1' \
	'-DENABLE_REGISTER_PROTOCOL_HANDLER=1' \
	'-DWEBRTC_TARGET_PC' \
	'-DWEBRTC_LINUX' \
	'-DWEBRTC_THREAD_RR' \
	'-DNETEQ_VOICEENGINE_CODECS' \
	'-DSCRATCH' \
	'-D__STDC_FORMAT_MACROS' \
	'-DNDEBUG' \
	'-DNVALGRIND' \
	'-DDYNAMIC_ANNOTATIONS_ENABLED=0'

# Flags passed to all source files.
CFLAGS_Release := -Werror \
	-pthread \
	-fno-exceptions \
	-Wall \
	-Wno-unused-parameter \
	-Wno-missing-field-initializers \
	-D_FILE_OFFSET_BITS=64 \
	-fvisibility=hidden \
	-pipe \
	-fPIC \
	-fno-strict-aliasing \
	-O2 \
	-fno-ident \
	-fdata-sections \
	-ffunction-sections

# Flags passed to only C files.
CFLAGS_C_Release := 

# Flags passed to only C++ files.
CFLAGS_CC_Release := -fno-rtti \
	-fno-threadsafe-statics \
	-fvisibility-inlines-hidden \
	-Wsign-compare

INCS_Release := -Isrc \
	-I. \
	-Isrc/modules/audio_coding/NetEQ/main/interface \
	-Isrc/modules/audio_coding/codecs/CNG/main/interface \
	-Isrc/common_audio/signal_processing_library/main/interface

OBJS := $(obj).target/$(TARGET)/src/modules/audio_coding/NetEQ/main/source/accelerate.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/NetEQ/main/source/automode.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/NetEQ/main/source/bgn_update.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/NetEQ/main/source/bufstats_decision.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/NetEQ/main/source/cng_internal.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/NetEQ/main/source/codec_db.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/NetEQ/main/source/correlator.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/NetEQ/main/source/dsp.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/NetEQ/main/source/dsp_helpfunctions.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/NetEQ/main/source/dtmf_buffer.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/NetEQ/main/source/dtmf_tonegen.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/NetEQ/main/source/expand.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/NetEQ/main/source/mcu_address_init.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/NetEQ/main/source/mcu_dsp_common.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/NetEQ/main/source/mcu_reset.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/NetEQ/main/source/merge.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/NetEQ/main/source/min_distortion.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/NetEQ/main/source/mix_voice_unvoice.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/NetEQ/main/source/mute_signal.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/NetEQ/main/source/normal.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/NetEQ/main/source/packet_buffer.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/NetEQ/main/source/peak_detection.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/NetEQ/main/source/preemptive_expand.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/NetEQ/main/source/random_vector.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/NetEQ/main/source/recin.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/NetEQ/main/source/recout.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/NetEQ/main/source/rtcp.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/NetEQ/main/source/rtp.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/NetEQ/main/source/set_fs.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/NetEQ/main/source/signal_mcu.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/NetEQ/main/source/split_and_insert.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/NetEQ/main/source/unmute_signal.o \
	$(obj).target/$(TARGET)/src/modules/audio_coding/NetEQ/main/source/webrtc_neteq.o

# Add to the list of files we specially track dependencies for.
all_deps += $(OBJS)

# CFLAGS et al overrides must be target-local.
# See "Target-specific Variable Values" in the GNU Make manual.
$(OBJS): TOOLSET := $(TOOLSET)
$(OBJS): GYP_CFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE)) $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_C_$(BUILDTYPE))
$(OBJS): GYP_CXXFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE)) $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_CC_$(BUILDTYPE))

# Suffix rules, putting all outputs into $(obj).

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(srcdir)/%.c FORCE_DO_CMD
	@$(call do_cmd,cc,1)

# Try building from generated source, too.

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj).$(TOOLSET)/%.c FORCE_DO_CMD
	@$(call do_cmd,cc,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj)/%.c FORCE_DO_CMD
	@$(call do_cmd,cc,1)

# End of this set of suffix rules
### Rules for final target.
LDFLAGS_Debug := -pthread \
	-Wl,-z,noexecstack

LDFLAGS_Release := -pthread \
	-Wl,-z,noexecstack \
	-Wl,-O1 \
	-Wl,--as-needed \
	-Wl,--gc-sections

LIBS := 

$(obj).target/src/modules/libNetEq.a: GYP_LDFLAGS := $(LDFLAGS_$(BUILDTYPE))
$(obj).target/src/modules/libNetEq.a: LIBS := $(LIBS)
$(obj).target/src/modules/libNetEq.a: TOOLSET := $(TOOLSET)
$(obj).target/src/modules/libNetEq.a: $(OBJS) FORCE_DO_CMD
	$(call do_cmd,alink)

all_deps += $(obj).target/src/modules/libNetEq.a
# Add target alias
.PHONY: NetEq
NetEq: $(obj).target/src/modules/libNetEq.a

# Add target alias to "all" target.
.PHONY: all
all: NetEq

