/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

# Sunbird User Preferences

/* Do not edit this file while Sunbird is running. If you do so, the changes
 * will be overwritten when the you quit Sunbird.
 *
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */
pref("app.vendorURL", "http://www.mozilla.org/projects/%APP%/");
