# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := merged_lib_voice
### Rules for action "merge_libs":
quiet_cmd_merged_lib_voice_merge_libs = ACTION merged_lib_voice_merge_libs $@
cmd_merged_lib_voice_merge_libs = export LD_LIBRARY_PATH=$(builddir)/lib.host:$(builddir)/lib.target:$$LD_LIBRARY_PATH; cd src/voice_engine; mkdir -p $(builddir); python ../build/merge_libs.py "$(builddir)" "$(builddir)/libwebrtc_voice_engine_linux.a"

$(builddir)/libwebrtc_voice_engine_linux.a: obj := $(abs_obj)

$(builddir)/libwebrtc_voice_engine_linux.a: builddir := $(abs_builddir)

$(builddir)/libwebrtc_voice_engine_linux.a: TOOLSET := $(TOOLSET)
$(builddir)/libwebrtc_voice_engine_linux.a: $(builddir)/voe_auto_test FORCE_DO_CMD
	$(call do_cmd,merged_lib_voice_merge_libs)

all_deps += $(builddir)/libwebrtc_voice_engine_linux.a
action_merged_lib_voice_merge_libs_outputs := $(builddir)/libwebrtc_voice_engine_linux.a


### Rules for final target.
# Build our special outputs first.
$(obj).target/src/voice_engine/merged_lib_voice.stamp: | $(action_merged_lib_voice_merge_libs_outputs)

# Preserve order dependency of special output on deps.
$(action_merged_lib_voice_merge_libs_outputs): | $(builddir)/voe_auto_test

$(obj).target/src/voice_engine/merged_lib_voice.stamp: TOOLSET := $(TOOLSET)
$(obj).target/src/voice_engine/merged_lib_voice.stamp: $(builddir)/voe_auto_test FORCE_DO_CMD
	$(call do_cmd,touch)

all_deps += $(obj).target/src/voice_engine/merged_lib_voice.stamp
# Add target alias
.PHONY: merged_lib_voice
merged_lib_voice: $(obj).target/src/voice_engine/merged_lib_voice.stamp

