/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*-
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

/*

  The Sidebar API for 3rd parties

*/

#include "nsISupports.idl"

[scriptable, uuid(e0f4c5ee-2b35-4e99-81d2-ab956c4de0d1)]
interface nsISidebarPanel : nsISupports
{
    void addPanel(in DOMString aTitle, in DOMString aContentURL,
                  in DOMString aCustomizeURL);
    void addPersistentPanel(in DOMString aTitle, in DOMString aContentURL,
                            in DOMString aCustomizeURL);
};
