/* -*- Mode: IDL; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 2 -*- */
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */


#include "nsISupports.idl"

interface nsIFile;
interface nsIMsgFolderCacheElement;

[scriptable, uuid(78C2B6A2-E29F-44de-9543-10DBB51E245C)]
interface nsIMsgFolderCache : nsISupports 
{
  void Init(in nsIFile aFile);
  nsIMsgFolderCacheElement GetCacheElement(in ACString key, in boolean createIfMissing);
  void clear();
  void close();
  void commit(in boolean compress);
  void removeElement(in ACString key);
};
