/* -*- Mode: IDL; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 2 -*- */
/* ***** BEGIN LICENSE BLOCK *****
 * Version: MPL 1.1/GPL 2.0/LGPL 2.1
 *
 * The contents of this file are subject to the Mozilla Public License Version
 * 1.1 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 * http://www.mozilla.org/MPL/
 *
 * Software distributed under the License is distributed on an "AS IS" basis,
 * WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
 * for the specific language governing rights and limitations under the
 * License.
 *
 * The Original Code is mozilla.org code.
 *
 * The Initial Developer of the Original Code is
 * Netscape Communications Corporation.
 * Portions created by the Initial Developer are Copyright (C) 1999
 * the Initial Developer. All Rights Reserved.
 *
 * Contributor(s):
 *   Joshua Cranmer <Pidgeot18@gmail.com>
 *
 * Alternatively, the contents of this file may be used under the terms of
 * either of the GNU General Public License Version 2 or later (the "GPL"),
 * or the GNU Lesser General Public License Version 2.1 or later (the "LGPL"),
 * in which case the provisions of the GPL or the LGPL are applicable instead
 * of those above. If you wish to allow use of your version of this file only
 * under the terms of either the GPL or the LGPL, and not to allow others to
 * use your version of this file under the terms of the MPL, indicate your
 * decision by deleting the provisions above and replace them with the notice
 * and other provisions required by the GPL or the LGPL. If you do not delete
 * the provisions above, a recipient may use your version of this file under
 * the terms of any one of the MPL, the GPL or the LGPL.
 *
 * ***** END LICENSE BLOCK ***** */


#include "nsISupports.idl"

/**
 * An element of the folder cache.
 *
 * By convention, a separate element is used for each .msf file in the account
 * manager.
 *
 * Since the folder cache is expected to be backed by a database, each method
 * of this cache element (the key excluded) may throw a database-based error.
 */
[scriptable, uuid(D7ED2508-A608-46cd-AA01-FBB019B0FA44)]
interface nsIMsgFolderCacheElement : nsISupports 
{
  /**
   * The key of this element.
   *
   * By convention, this key is the name and path of the summary file that this
   * cache element represents.
   */
  attribute ACString key;
  /**
   * Gets a string for the named property.
   *
   * @param propertyName  The name of the property to get.
   * @return              The property value, or "" if it does not exist.
   *
   * @throws NS_ERROR_NULL_POINTER if propertyName is null.
   * @throws NS_ERROR_FAILURE      if the property does not exist.
   */
  ACString getStringProperty(in string propertyName);
  /**
   * Gets a long for the named property.
   *
   * @param propertyName  The name of the property to get.
   * @return              The property value, or 0 if it does not exist.
   *
   * @throws NS_ERROR_NULL_POINTER if propertyName is null.
   * @throws NS_ERROR_FAILURE      if the property does not exist.
   */
  long getInt32Property(in string propertyName);
  /**
   * Sets the named property.
   *
   * @param propertyValue The new value of the property to set.
   * @param propertyName  The name of the property to set.
   *
   * @throws NS_ERROR_NULL_POINTER if propertyName is null.
   */
  void setStringProperty(in string propertyName, in ACString propertyValue);
  /**
   * Sets the named property.
   *
   * @param propertyValue The new value of the property to set.
   * @param propertyName  The name of the property to set.
   *
   * @throws NS_ERROR_NULL_POINTER if propertyName is null.
   */
  void setInt32Property(in string propertyName, in long propertyValue);
};
