/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"
#include "nsIMsgWindow.idl"

[scriptable, uuid(BB460DFE-8BF0-11d3-8AFE-0060B0FC04D2)]

/*  Interface used to access functions particular to mailnews datasources */

interface nsIMsgRDFDataSource :  nsISupports
{
  attribute nsIMsgWindow window;
};
