/* -*- Mode: IDL; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"
#include "nsIMsgStatusFeedback.idl"
#include "nsIMessageView.idl"

interface nsITransactionManager;

/*
 *  This interface can be used to set data specific to a window.
 */


[scriptable, uuid(BD85A416-5433-11d3-8AC5-0060B0FC04D2)]
interface nsIMsgWindowData : nsISupports {

  attribute nsIMsgStatusFeedback statusFeedback;
    attribute nsITransactionManager transactionManager;
  attribute nsIMessageView messageView;
};