/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"

interface nsIDOMWindow;

/**
 * This interface provides support for registering Mozilla as the default
 * Mail Client. This interface can also be used to get/set the user preference
 * for the default Mail Client.
 * 
 */

[scriptable, uuid(B0342CA7-CB85-4d13-AD18-BD431F2086EA)]
interface nsIMapiRegistry: nsISupports {

   /** This is set to TRUE if Mozilla is the default mail application
    */
   attribute boolean isDefaultMailClient;

   /* Set to TRUE if Mozilla is the default news application */
   attribute boolean isDefaultNewsClient;

   /* Set to TRUE if we are the default feed/rss application */
   attribute boolean isDefaultFeedClient;

   /** This is set TRUE only once per session.
    */
   readonly attribute boolean showDialog;

   /** This will bring the dialog asking the user if he/she wants to set
    * Mozilla as default Mail Client.
    * Call this only if Mozilla is not the default Mail client
    */
   void showMailIntegrationDialog(in nsIDOMWindow parentWindow);

   /* After being installed, when we first launch, make sure we add the correct
    OS registry entries to make us show up as regsitered mail and news client
    in the OS
   */
   
   void registerMailAndNewsClient();
};

%{C++
#define NS_IMAPIREGISTRY_CONTRACTID    "@mozilla.org/mapiregistry;1"
#define NS_IMAPIREGISTRY_CLASSNAME "Mozilla MAPI Registry"
%}
