/* -*- Mode: IDL; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 2 -*- */
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */


#include "nsISupports.idl"

[scriptable, uuid(D7ED2508-A608-46cd-AA01-FBB019B0FA44)]
interface nsIMsgFolderCacheElement : nsISupports 
{
  attribute ACString key;
  ACString getStringProperty(in string propertyName);
  long getInt32Property(in string propertyName);
  void setStringProperty(in string propertyName, in ACString propertyValue);
  void setInt32Property(in string propertyName, in long propertyValue);
};
