# This file is generated by gyp; do not edit.

export builddir_name ?= trunk/src/system_wrappers/source/$(OBJDIR)/media/webrtc/out
.PHONY: all
all:
	$(MAKE) -C ../../.. system_wrappers system_wrappers_unittests
